version: 0.2

phases:
  install:
    commands:
      - echo "Installing nginx..."
      - sudo apt-get update -y
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo "Building the project..."
      - cp index.html /var/www/html/
  post_build:
    commands:
      - echo "configuring NGINX"

artifacts:
  files:
    - /var/www/html/index.html
    
